[book]
authors = ["ChiangYintso"]
language = "en"
multilingual = false
src = "doc"
title = "ICPC wiki"

[output.html]
mathjax-support = true

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]
marker = "[TOC]"
